const url = 'http://localhost:3000';
const title = 'coffmanjrp.io';
const description = 'Generated by create next app';

const SEO = {
  title,
  description,
  canonical: url,
  openGraph: {
    type: 'website',
    locale: 'en_IE',
    url,
    title,
    description,
    images: [
      {
        url: `${url}/og.png`,
        alt: title,
        width: 1280,
        height: 720,
      },
    ],
  },
  additionalLinkTags: [
    {
      rel: 'icon',
      href: `/favicon.ico`,
    },
  ],
};

export default SEO;
